name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install the required python packages
        run: python -m pip install linkml, mkdocs, mkdocs-material, mkdocs-redirects, mkdocs-minify-plugin, mkdocs-git-revision-date-localized-plugin, mkdocs-awesome-pages-plugin, mkdocs-macros-plug

      -name: generating linkml docs
        run: gen-doc -d docs/linkml linkml-schema/reproschema.yam

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
